import os
import sys
import glob
import argparse
from PIL import Image, ImageEnhance
import xml.etree.ElementTree as ET

import params as p

IMAGE_PATH = "./images/"
PAGE_PATH = "./pages/"
XML_PATH = "./xml/"

"""
A Python script for placing Magic: The Gathering card images onto printable pages.

The script processes card images and a corresponding `.xml` file generated by MPCFill 
to produce ready-to-print `.jpg` pages. Each page contains a grid of card fronts, with 
optional separate pages for card backs to support printing double-sided cards.

The `.xml` file is required to correctly pair front and back images. Output pages are 
optimized for home printing or professional services. Most parameters can be customized 
via command-line arguments.

Typical use case:
    - Download card images and `.xml` from MPCFill 
    - Place images into images/ and `.xml` into xml/
    - Run this script to generate `.jpg` print pages
    - Print using standard or duplex printing, depending on back design
"""

class Page:
    """A virtual page onto which the card images are placed

    This represents a single page containing cards and is used to
    manipulate the images (cropping, resizing etc.) and ensuring 
    that the cards print out to the right size. 
    """
    def __init__(self, args, is_back=False):
        """Initialise the page.
            
        Args:
            args (Object): Command-line arguments from user.
            is_back (bool): True if this page contains the back side of cards.
        """
        self.is_back = is_back

        self.card_width = p.card_widths[args.quality]
        self.card_height = int(p.card_ratio * self.card_width)

        #Space between cards.
        if args.spacing_x is None:
            self.spacing_x = convert_mm_to_pixels(self.card_width, args.spacing)
        else:
            self.spacing_x = convert_mm_to_pixels(self.card_width, args.spacing_x)
        if args.spacing_y is None:
            self.spacing_y = convert_mm_to_pixels(self.card_width, args.spacing)
        else:
            self.spacing_y = convert_mm_to_pixels(self.card_width, args.spacing_y)


        #Bleed around cards, either added by MPCFill or added later to help
        #decrease visibility of misalignment on two sided cards.
        self.card_bleed_w = convert_mm_to_pixels(self.card_width, args.bleed)
        self.card_bleed_h = int(self.card_bleed_w)

        #Amount to crop the cards, default is equal to bleed.
        self.crop_w = convert_mm_to_pixels(self.card_width, args.crop_width)
        self.crop_h = convert_mm_to_pixels(self.card_width, args.crop_height)

        #Size of crop marks added to aid with cutting on cards with preserved bleed
        self.crop_mark_size = convert_mm_to_pixels(self.card_width, args.crop_mark_size)

        #Amount of brightning applied to cards, helps when some printers print
        #dark.
        self.brightness_adjust = args.brightness_adjust

        self.page_size = args.page_size.lower()
        self.page_width = convert_mm_to_pixels(
            self.card_width, p.get_page_widths(self.page_size)
        )
        self.page_height = int(p.page_ratio * self.page_width)

        #Reset page
        self.clear_page()

        #Find the number of rows and columns this page can hold
        self.calculate_rows_and_cols()


    def calculate_rows_and_cols(self):
        #Number of rows and columns, set by the page size e.g a4 pages can hold 
        #3x3 mtg cards.
        if self.has_back or self.is_back:
            self.columns = self.page_width // (self.card_width + 2 * self.card_bleed_w + self.spacing_x)
            self.rows = self.page_height // (self.card_height + 2 * self.card_bleed_h + self.spacing_y)
        else:
            self.columns = self.page_width // (self.card_width + self.spacing_x)
            self.rows = self.page_height // (self.card_height + self.spacing_y)

        #Margins around edge of page, derived by the negative space left by other
        #variables.
        self.margin_w = int(
            0.5
            * (
                self.page_width
                - self.columns * self.card_width
                - (self.columns - 1) * self.spacing_x
            )
        )
        self.margin_w = max(p.margin_w_min, self.margin_w)

        self.margin_top = int(
            0.5
            * (
                self.page_height
                - self.rows * self.card_height
                - (self.rows - 1) * self.spacing_y
            )
        )
        self.margin_w = max(p.margin_w_min, self.margin_w)

    def clear_page(self):
        """Create empty page and reset associated variables"""
        self.page = Image.new(
            mode="RGB",
            size=(self.page_width, self.page_height),
            color=(255,255,255) #type: ignore
        )
        self.is_empty = True
        self.is_full = False
        self.has_back = False
        self.calculate_rows_and_cols()
        self.current_row = 0
        self.current_col = 0

    def resize_image(self, image, keep_bleed=False):
        """Resizes images to the predefined card width so 
        that the cards are the right size when printing. 
        Can optionally allow the cards to keep the bleed that
        MPCFill adds.

        Args:
            image (PIL.Image): image of card
            keep_bleed (bool): resize card to correct size plus
                               the bleed around the edges 
        """
        if keep_bleed:
            return image.resize(
                (
                    self.card_width + 2 * self.card_bleed_w,
                    self.card_height + 2 * self.card_bleed_h,
                )
            )
        else:
            return image.resize((self.card_width, self.card_height))

    def crop_image(self, image):
        """Crops the bleed that MPCFill adds to cards

        Args:
            image (PIL.Image): image of card
        """
        left = self.crop_w
        right = self.card_width + 2 * self.card_bleed_w - self.crop_w
        upper = self.crop_h
        lower = self.card_height + 2 * self.card_bleed_h - self.crop_h
        return image.crop((left, upper, right, lower))
    
    def add_bleed(self, image):
        """Non-MPCFill cards might not have the bleed but we want to
        have bleed on pages that have a back side (for double-sided
        cards and to allow for misalignment in prints) so we add the 
        bleed here.

        Args:
            image (PIL.Image): image of card
        """
        border = Image.new(
            mode="RGB",
            size=(
                self.card_width + 2 * self.card_bleed_w,
                self.card_height + 2 * self.card_bleed_h,
            ),
            color=(0,0,0), #type: ignore
        )
        border.paste(
            image,
            (self.card_bleed_w, self.card_bleed_h),
        )

        return border

    def add_crop_marks(self, x, y):
        """Add visual crop marks to guide cutting when bleed is present.
        
        Draws small squares at each corner of the card using a black border
        with a white interior, ensuring visibility on any background.

        Args:
            x (int): x pixel position of top left corner of card
            y (int): y pixel position of top left corner of card
        """
        x_b = x + self.card_bleed_w
        y_b = y + self.card_bleed_h
        crop_marks = [
            (x_b, y_b),
            (x_b + self.card_width, y_b),
            (x_b, y_b + self.card_height),
            (x_b + self.card_width, y_b + self.card_height),
        ]

        crop_mark_size = max(2, self.crop_mark_size)
        crop_mark_half = crop_mark_size // 2
        outline_width = max(2, self.crop_mark_size // 4)

        for cx, cy in crop_marks:
            for dx in range(-crop_mark_half, crop_mark_half):
                for dy in range(-crop_mark_half, crop_mark_half):
                    #Is pixel inside border
                    if (
                        abs(dx) >= crop_mark_half - outline_width or
                        abs(dy) >= crop_mark_half - outline_width
                    ):
                        pixel_colour = (0, 0, 0)
                    else:
                        pixel_colour = (255, 255, 255)

                    self.page.putpixel((cx + dx, cy + dy), pixel_colour)

    def add_image_to_page(self, card, is_back=False):
        """Paste a card image onto the page at the correct size.

        Args:
            card (Card): Card object.
            is_back (bool): True if adding the image of the back of the card.
        """
        if is_back:
            image = Image.open(card.image_back)
        else:
            image = Image.open(card.image)

        if self.has_back or is_back:
            keep_bleed = True
        else:
            keep_bleed = False

        #Ensure correct cropping and sizing of cards
        if card.has_bleed:
            image = self.resize_image(image, keep_bleed=True)
            if not keep_bleed:
                image = self.crop_image(image)
        else:
            image = self.resize_image(image)
            if keep_bleed:
                image = self.add_bleed(image)

        #Modify brightness of image
        enhancer = ImageEnhance.Brightness(image)
        image = enhancer.enhance(self.brightness_adjust)

        #x and y are the pixel positions on the page which define where the
        #top left corner of the image will be placed.
        if keep_bleed:
            x = (
                self.margin_w
                - self.columns * self.card_bleed_w
                + self.current_col
                * (self.card_width + 2 * self.card_bleed_w + self.spacing_x)
            )
            y = (
                self.margin_top
                - self.rows * self.card_bleed_h
                + self.current_row
                * (self.card_height + 2 * self.card_bleed_h + self.spacing_y)
            )
        else:
            x = self.margin_w + self.current_col * (self.card_width + self.spacing_x)
            y = self.margin_top + self.current_row * (self.card_height + self.spacing_y)

        #Place card image onto page
        self.page.paste(image, (x, y))

        if keep_bleed:
            self.add_crop_marks(x, y)

        self.is_empty = False
        self.current_col += 1

        if self.current_col >= self.columns:
            self.current_col = 0
            self.current_row += 1

        if self.current_row >= self.rows:
            self.is_full = True


    def save_page(self, filename):
        self.page.save(filename)


class Card:
    """Container for card information, extracted from .xml file."""
    def __init__(self, card, back=None, instances=1):
        """Initialise the card

        Args:
            card (ElementTree): xml object containing card information.
            back (ElementTree or None): xml object containing information 
                                        for the back of the card, if any.
            instances (int): number of copies of this card.
        """
        self.card = card
        self.instances = instances

        self.id = self.card.find("id").text
        self.image = self.find_card_images(self.id)
        self.name = self.card.find("name").text.title()

        #Non MPCFill cards should be marked with an id made only of
        #x. It is assumed that such a card has no bleed.
        if set(self.id) == set("x"):
            self.has_bleed = False
        else:
            self.has_bleed = True

        if back is not None:
            self.back = back
            self.has_back = True
            try:
                self.id_back = self.back.find("id").text
                self.name_back = self.back.find("name").text.title()
            except AttributeError:
                self.id_back = self.back.text
                self.name_back = "Card Back"
            self.image_back = self.find_card_images(self.id_back)
        else:
            self.back = None
            self.id_back = None
            self.image_back = None
            self.name_back = ""
            self.has_back = False

    def __repr__(self):
        if self.has_back:
            return f"{self.name} // {self.name_back}"
        else:
            return self.name 

    def find_card_images(self, card_id):
        """Find path to image based on the card id

        Args:
            card_id (str): The card's unique id.
        """
        for card_image in os.listdir(IMAGE_PATH):
            if "Zone.Identifier" in card_image:
                continue
            if "put_card_images_here" in card_image:
                continue

            import re

            #Regex: All characters within the last pair of brackets followed by a .
            #BUG: Copies of a file in windows add a (#) before the extension. Regex picks that up instead of id.
            
            try:
                id = re.findall(r"\((?=[^\(]*$).*(?=\)\.)", card_image)[-1][1:]
            except IndexError:
                raise Exception(f"{self.name} or {self.name_back} not found!")

            if id == card_id:
                return IMAGE_PATH + card_image



def parse_args():
    """Create and handle command-line arguments."""
    parser = argparse.ArgumentParser(description="Page Maker")
    parser.add_argument("-s", "--spacing", type=float, default=p.spacing_default)
    parser.add_argument("-sx", "--spacing-x", type=float, default=None)
    parser.add_argument("-sy", "--spacing-y", type=float, default=None)
    parser.add_argument("-b", "--bleed", type=float, default=p.bleed_default)
    parser.add_argument("-p", "--page-size", default=p.page_size_default)
    parser.add_argument("-ch", "--crop-height", type=float, default=p.crop_h_default)
    parser.add_argument("-cw", "--crop-width", type=float, default=p.crop_w_default)
    parser.add_argument("--brightness-adjust", type=float, default=p.brightness_adjust_default)
    parser.add_argument("--card-backs", action="store_true", default=p.card_backs_default)

    parser.add_argument(
        "-q", "--quality",
        choices=["low", "medium", "high"],
        default="high"
    )
    parser.add_argument(
        "--crop_mark_size",
        type=float,
        default=p.crop_mark_size_default
    )
    return parser.parse_args()


def convert_mm_to_pixels(card_width, mm):
    """Converts from millimetres to pixels on the page. The card width is a known
    quantity: mtg cards are 63mm wide. So we use it for conversion.
    """
    pixels_per_mm = card_width / p.card_width_in_mm
    return int(mm * pixels_per_mm)


def convert_pixels_to_mm(card_width, pixels):
    """Converts from pixels on the page to millimetres. The card width is a known
    quantity: mtg cards are 63mm wide. So we use it for conversion.
    """
    mm_per_pixel = p.card_width_in_mm / card_width
    return pixels * mm_per_pixel

def check_all_cards_are_present():
    """
    Sometimes mpcfill misses an image download for some reason so this checks
    if all of the images for the cards in the .xml are present. Raises an
    exception with a list of missing cards if any.
    """

    def card_compare(card_id):
        """Return true if there is an image in the image folder matching card_id,
        else false
        """
        for image_name in os.listdir(IMAGE_PATH):
            if card_id in image_name:
                return True
        return False

    with open(XML_PATH + "cards.xml") as f:
        root = ET.parse(f).getroot()
        cards = root.find("fronts")

    if cards is None:
        raise Exception("No cards found!")

    not_found = []

    for card in cards:
        card_id = card.find("id")
        card_name = card.find("name")
        if card_id is not None:
            card_id = card_id.text
        else:
            raise Exception("ID missing on some cards!")
        if card_name is not None:
            card_name = card_name.text
        else:
            raise Exception("Name missing on some cards!")

        if not card_compare(card_id):
            not_found.append(card_name)

    if not_found == []:
        print("All cards present!")
    else:
        raise Exception(f"The following cards are missing: {not_found}")


def clear_pages_folder():
    """
    Remove old pages from pages folder.
    """
    os.makedirs(PAGE_PATH, exist_ok=True)
    pages = glob.glob(PAGE_PATH + "*")
    for i in pages:
        os.remove(i)


def save_pages(page, back, name):
    """Save pages with naming: (name).jpg or (name)_back.jpg

    Args:
        page (Page): Page object containing card fronts.
        back (Page): Page object containing card backs
        name (int): Page number, used for the name of the .jpg
    """
    page.save_page(PAGE_PATH + f"/{name}.jpg")

    if page.has_back:
        back.save_page(PAGE_PATH + f"/{name}_back.jpg")

    back.clear_page()
    page.clear_page()

def add_card(card, page, page_back):
    """Adds card image to page, also add back side of card to a seperate
    page, if applicable.

    Args:
        card (Card): Card object containing card information
        page (Page): Page object containing card fronts
        page_back (Page): Page object containing card backs
    """
    print(f"Adding {card.card.find('query').text.title()}")

    if card.image is None:
        raise Exception(f'Image for "{card.name}" not found')

    if card.back is not None:
        if card.image_back is None:
            raise Exception(f'Image for "{card.name_back}" not found')

    if card.back is None:
        page.add_image_to_page(card)
    else:
        page_back.current_row = page.current_row
        page_back.current_col = page.columns - 1 - page.current_col

        page.add_image_to_page(card)
        page_back.add_image_to_page(card, is_back=True)


def create_cards(args):
    """Finds card information from .xml file and creates a list of Card objects
    from it.

    Args:
        args (ArgumentParser): Object containing command-line arguments.

    Returns:
        list[Card]: List of Card objects, each representing a unique card.
    """
    with open(XML_PATH + "cards.xml") as f:
        root = ET.parse(f).getroot()
        cards = root.find("fronts")
        backs = root.find("backs")
        generic_card_back = root.find("cardback")

    if cards is None:
        raise Exception("No cards found.")
    if backs is None:
        backs = []

    card_objs = []

    slots_back_map = []
    for back in backs:
        if (slots_elem := back.find("slots")) is not None and slots_elem.text is not None:
            slots_back_map.append((back, set(slots_elem.text.split(","))))
        else:
            raise Exception("A card is missing slot information!")

    for card in cards:
        if (slots_elem := card.find("slots")) is not None and slots_elem.text is not None:
            slots = set(slots_elem.text.split(","))
        else:
            raise Exception("A card is missing slot information!")

        for back, slots_back in slots_back_map:
            if slots & slots_back:
                card_objs.append(Card(card, back=back, instances=len(slots)))
                break
        else:
            if args.card_backs:
                card_objs.append(Card(card, back=generic_card_back, instances=len(slots)))
            else:
                card_objs.append(Card(card, instances=len(slots)))


    #Place all cards with backs first, minimising the number of 2-sided pages.
    return sorted(card_objs, key=lambda x: x.has_back, reverse=True)


def batch_cards(cards, page):
    """Creates a list containing a page's worth of cards. Useful for
    determining whether the page should have a back side or not.

    Args:
        cards list[Card]: A list containing all cards not currently on a page
        page (Page): Page object containing card fronts
    """
    batch = []
    for card in cards:
        for _ in range(card.instances):
            batch.append(card)
            if card.has_back:
                page.has_back = True
                page.calculate_rows_and_cols()
            if len(batch) >= page.rows * page.columns:
                return batch[:page.rows * page.columns]
    return batch

def add_card_to_page(batch, cards, page, page_back):
    """Adds cards in current batch to page, then removes the card
    from the list, or decrements the number of copies.

    Args:
        batch list[Card]: A list containing one page worth of card objects.
        cards list[Card]: A list containing all cards not currently on a page.
        page (Page): Page object containing card fronts
        page_back (Page): Page object containing card backs
    """
    for card in batch:
        add_card(card, page, page_back)
        card.instances -= 1

        if card.instances <= 0:
            cards.remove(card)


def create_pages(args):
    """Creates pages and populates them with card images, then saves them as a jpg.

    Args:
        args (ArgumentParser): Object containing command-line arguments.
    """
    page = Page(args)
    page_back = Page(args, is_back=True)

    page_count = 1

    cards = create_cards(args)
    batch = batch_cards(cards, page)

    while len(cards) > 0:
        if page.is_empty:
            print(f"Creating page {page_count}...")
        add_card_to_page(batch, cards, page, page_back)

        if page.is_full:
            print()
            print(f"Saving page {page_count}... ", end="", flush=True)
            save_pages(page, page_back, page_count)
            print("Saved!")
            print()

            page_count += 1
        
        batch = batch_cards(cards, page)

    if not page.is_empty:
        print(f"Saving page {page_count}... ", end="")
        save_pages(page, page_back, page_count)
        print("Saved!")

def handle_errors(args):
    import re
    if not re.match(r"^[abc]{1}\d{1}$", args.page_size.lower()):
        print(f"{args.page_size} page size not supported. Use A4, B3, C5 etc.")
        sys.exit(1)

    page_size_number = int(args.page_size[1:])
    if (page_size_number > p.MAX_PAGE_SIZE_NUMBER
        or page_size_number < p.MIN_PAGE_SIZE_NUMBER):
        print("Page size too small! Try a larger page.")
        sys.exit(1)


def main():
    args = parse_args()
    handle_errors(args)
    check_all_cards_are_present()
    clear_pages_folder()
    create_pages(args)


if __name__ == "__main__":
    main()
