from src.cli_args_manager import CLIArgsManager
from src.card_maker import create_cards
from src.page_maker import page_maker

import src.params as params
import src.helpers as helpers

'''
A Python script for placing Magic: The Gathering card images onto printable pages.

The script processes card images and a corresponding `.xml` file generated by MPCFill 
to produce ready-to-print `.jpg` pages. Each page contains a grid of card fronts, with 
optional separate pages for card backs to support printing double-sided cards. All parameters
can be configured either in params.py or using command-line arguments.

Downloads card images from Google Drive or loads from disk if already present in IMAGE_PATH.
Also allows non-MPCFill cards to be used by placing them in the CUSTOM_IMAGES folder.

The `.xml` file is required to correctly pair front and back images. Output pages are 
optimized for home printing or professional services. Most parameters can be customized 
via command-line arguments.

Typical use case:
    - Download `cards.xml` from MPCFill 
    - Place any custom images into data/custom_images/ and `.xml` into data/xml/
    - Run this script to generate `.jpg` print pages and optionally aggregated `.pdf`
    - Print using standard or duplex printing, depending on back design
'''

def main(argv=None):
    # Get command-line arguments
    args = CLIArgsManager(argv).get_cli_args()

    # Clear out old pages from PAGE_PATH
    helpers.clear_folder(params.PAGE_PATH)

    # Create double-sided card objects 
    cards = create_cards(args)

    # Create and save pages to PAGE_PATH
    page_maker(args, cards)

if __name__ == '__main__':
    main()
