import questionary

from pathlib import Path
from src.page import Page 
from src.card import Card, DoubleSidedCard
from src.card_parser import CardParser
from src.cli_args_manager import CLIArgsManager, CLIArgs
from PIL.Image import Image as PILImageType

import src.get_images as get_images
import xml.etree.ElementTree as ET
import src.params as params
import src.helpers as helpers


'''
A Python script for placing Magic: The Gathering card images onto printable pages.

The script processes card images and a corresponding `.xml` file generated by MPCFill 
to produce ready-to-print `.jpg` pages. Each page contains a grid of card fronts, with 
optional separate pages for card backs to support printing double-sided cards.

The `.xml` file is required to correctly pair front and back images. Output pages are 
optimized for home printing or professional services. Most parameters can be customized 
via command-line arguments.

Typical use case:
    - Download card images and `.xml` from MPCFill 
    - Place any custom images into custom_images/ and `.xml` into xml/
    - Run this script to generate `.jpg` print pages
    - Print using standard or duplex printing, depending on back design
'''

def clear_pages_folder():
    '''
    Remove old pages from pages folder.
    '''
    params.PAGE_PATH.mkdir(exist_ok=True)
    for page in params.PAGE_PATH.glob('*'):
        Path.unlink(page)


def save_pages(page: Page, name: str):
    '''Save pages with naming: (name).jpg or (name)_back.jpg

    Args:
        page (Page): Page object containing card fronts.
        back (Page): Page object containing card backs
        name (int): Page number, used for the name of the .jpg
    '''
    print()
    print(f'Saving page {name}... ', end='', flush=True)
    page.save_page(params.PAGE_PATH / f'{name}.jpg')
    print('Saved!')
    print()


def create_xml(id, slots, name, query):
    card = ET.Element("card")
    ET.SubElement(card, "id").text = id
    ET.SubElement(card, "slots").text = slots
    ET.SubElement(card, "name").text = name
    ET.SubElement(card, "query").text = query
    return card


def add_image_to_page_prompt(extra_images: list[str], cards: list[Card]) -> dict:
    '''Prompt user to assign images that don't have an id to be
    added or added as a back to another card.

    Args:
        extra_images list(str): list of images that don't have an id
        cards (list[Card]): list of Card objects
    '''
    image_pairs = {}
    for image in extra_images:
        if image in image_pairs:
            #Image has been chosen as front face of a previous image
            continue

        add_to_page = questionary.select(f'Would you like to add {image} as a front face or a back face?',
                choices=['front', 'back']).ask()

        if add_to_page == 'front':
            image_pairs[image] = ''

        elif add_to_page == 'back':
            card_name_map = {card.name:card for card in cards}
            choices = []
            for card_name in card_name_map:
                if card_name not in image_pairs:
                    choices.append(card_name)

            for other_image in extra_images:
                if other_image not in image_pairs and other_image not in image_pairs.values() and other_image != image:
                    choices.append(other_image)

            front_image = questionary.select(f'Which card would you like to add {image} to the back of?',
                    choices=sorted(choices)).ask()
            
            try:
                image_pairs[card_name_map[front_image].id] = image
            except KeyError:
                image_pairs[front_image] = image

    return image_pairs


def add_extra_images(cards: list[Card]) -> tuple[list[Card], list[Card]]:
    '''Search params.CUSTOM_IMAGE_PATH for images 
    prompt to ask the user if they want to add them.

    Args:
        cards (list[Card]): list of Card objects

    Returns:
        list[Card]: list of Card objects generated from images in CUSTOM_IMAGE_PATH
    '''
    extra_images = helpers.get_all_images_from_folder(params.CUSTOM_IMAGE_PATH)

    if not extra_images:
        return [], []

    image_pairs = add_image_to_page_prompt(extra_images, cards)
    
    extra_cards = []
    extra_backs = []
    slot_number = 1000
    x_count = 1

    for front, back in image_pairs.items():
        if back == '':
            name = str(front)
            id = 'x' * x_count
            slots = str(slot_number)

            card_xml = create_xml(
                id=id,
                slots=slots,
                name=name,
                query=name
            )

            card = CardParser(card_xml).extract_card()
            extra_cards.append(card)

        elif isinstance(front, str):
            name = str(back)
            id = 'x' * x_count
            slots = ",".join(next(card.slots for card in cards if card.id == front))
            card_xml = create_xml(
                id=id,
                slots=slots,
                name=name,
                query=name
            )

            card = CardParser(card_xml).extract_card()
            extra_backs.append(card)

        else:
            name = str(front)
            id = 'x' * x_count
            slots = str(slot_number)
            name_back = str(back)
            id_back = 'x' * x_count

            card_xml = create_xml(
                id=id,
                slots=slots,
                name=name,
                query=name
            )

            card_xml_back = create_xml(
                id=id_back,
                slots=slots,
                name=name_back,
                query=name_back
            )

            card = CardParser(card_xml).extract_card()
            back = CardParser(card_xml_back).extract_card()

            extra_cards.append(card)
            extra_backs.append(back)

        slot_number += 1
        x_count += 1

    return extra_cards, extra_backs


def create_card_dict(name: str|None, id: str|None, slots: str|None) -> dict: 
    if name is None or id is None or slots is None:
        raise Exception("Malformed Card")
    card = {
        'name': name,
        'id': id,
        'slots': slots,
        'query': name.lower()
    }
    return card


def get_cards_info_from_xml(xml: Path) -> tuple[list[Card], list[Card], Card]:
    '''
    Extracts card information from xml file

    Args:
        xml (Path): Path object containing path to xml file

    Returns:
        cards (ET.Element): XML object containing card information
        backs (ET.Element|None): XML object containing card information for back side of cards 
                                 or None if backs is absent
        generic_card_back (ET.Element): XML object containing information for generic back side of cards
    '''
    try:
        with open(xml) as f:
            root = ET.parse(f).getroot()
            cards_xml = root.find('fronts')
            backs_xml = root.find('backs')
            generic_card_back_id_xml = root.findtext('cardback')
    except ET.ParseError:
        raise Exception('XML file is empty!')

    if cards_xml is None:
        raise Exception('No cards found.')
    else:
        cards = []
        for card_xml in cards_xml.findall("card"):
            card = CardParser(card_xml).extract_card()
            cards.append(card)

    if backs_xml is None:
        backs = []
    else:
        backs = []
        for back_xml in backs_xml.findall("card"):
            back = CardParser(back_xml).extract_card()
            backs.append(back)

    if generic_card_back_id_xml is None:
        raise Exception('Generic card back id is missing.')
    else:
        generic_card_back_xml = create_xml(
            id=generic_card_back_id_xml,
            slots='-1',
            name='Generic card back.jpg',
            query='Generic card back'
        )
        generic_card_back = CardParser(generic_card_back_xml).extract_card()

    return cards, backs, generic_card_back


def remove_old_images(exceptions: list[Card]):
    image_paths = [card.image_path for card in exceptions]
    if params.IMAGE_PATH.is_dir():
        for image in params.IMAGE_PATH.iterdir():
            if image not in image_paths:
                image.unlink()


def assign_images_to_cards(cards: list[Card], card_images: dict[str, PILImageType]) -> None:
    '''
    Assigns card images to card objects, adding generic back image if given.

    Args:
        cards (list[Card]): List of card objects containing card information
        card_images (dict[str, PILImageType]): dict mapping card IDs to their corresponding images
    '''

    for card in cards:

        # Skip custom cards whose images come from CUSTOM_IMAGE_PATH and not
        # from get_images
        if card.id not in card_images:
            continue

        image = card_images[card.id]
        card.set_image(image)


def combine_front_and_backs(fronts: list[Card], backs: list[Card], generic_back: Card|None = None) -> list[DoubleSidedCard]:
    '''
    Combine Card objects describing the fron and the back of a card into one single
    Card object using the `slots` parameter as the matching criterion.

    Args:
        fronts (list[Card]): list of Card objects representing front sides
        backs (list[Card]): list of Card objects representing back sides
        generic_back (Card|None): Card object representing the generic back side of the cards
    Returns:
        (list[Card]): list of Card objects with backs attached if applicable
    '''
    cards = []
    for front in fronts:

        back = next(
            (b for b in backs if (set(front.slots) & set(b.slots))),
            None 
        )

        if back is not None:
            card = front // back
        elif generic_back is not None:
            card = front // generic_back
        else:
            card = front // None

        cards.append(card)

    return cards


def create_cards(args: CLIArgs) -> list[DoubleSidedCard]:
    '''Finds card information from .xml file and creates a list of Card objects
    from it.

    Args:
        args (CLIArgs): Object containing normalised command-line arguments.

    Returns:
        list[Card]: List of Card objects, each representing a unique card.
    '''

    # Transform card data from xml elements to Card objects
    fronts, backs, generic_back = get_cards_info_from_xml(params.XML_PATH / 'cards.xml')

    # Remove images from a previous run except those that are shared with this run
    remove_old_images(exceptions=fronts+backs+[generic_back])

    # Load in cards from CUSTOM_IMAGE_PATH
    extra_fronts, extra_backs = add_extra_images(fronts)

    fronts = fronts + extra_fronts
    backs = backs + extra_backs

    # Asynchronously load card images - downloading if necessary. 
    card_images = get_images.get_card_images(fronts + backs + [generic_back])

    # Add image to the Card objects
    assign_images_to_cards(fronts + backs + [generic_back], card_images)

    # Transform fronts and backs into single card objects
    if args.use_generic_card_backs:
        cards = combine_front_and_backs(fronts, backs, generic_back=generic_back)
    else:
        cards = combine_front_and_backs(fronts, backs, generic_back=None)

    #Place all cards with backs first, minimising the number of 2-sided pages.
    return sorted(cards, key=lambda x: x.back is not None, reverse=True)


def add_card_to_page(card: DoubleSidedCard, page: Page):
    '''Adds card image to page, also add back side of card to a seperate
    page, if applicable.

    Args:
        card (DoubleSidedCard): Object containing card information
        page (Page): Object containing card images
    '''
    print(f'Adding {card}')

    if not card.front.has_image:
        raise Exception(f'Image for {card.front.name} not found')

    if card.back is not None:
        if not card.back.has_image:
            raise Exception(f'Image for {card.back.name} not found')

    page.add_image_to_page(card)


def save_pages_as_pdf(pages: list[Page]):
    images = []
    for page in pages:
        images.append(page.page)
        if page.has_back:
            images.append(page.back)
    images[0].save(params.PAGE_PATH / 'cards.pdf', save_all=True, append_images=images[1:])


def calculate_number_of_pages(cards: list[DoubleSidedCard], args: CLIArgs) -> tuple[int, int]:
    '''
    The number of pages is nontrivial since the bleed on cards, defined at runtime, 
    may cause less cards to be able to fit on pages with backs than on pages without backs.

    Args:
        card (Card): List of card object containing card information
        args (CLIArgs): Instance of data class containing normalised command-line arguments

    Returns:
        (int): Total number of pages
        (int): Number of pages that have back sides
    '''
    cards_with_backs = sum((card.back is not None) * card.copies for card in cards)
    total_cards = sum(card.copies for card in cards)

    if args.always_bleed:
        cards_with_bleed = total_cards
    elif args.no_bleed:
        cards_with_bleed = 0
    else:
        cards_with_bleed = cards_with_backs

    cols_with_bleed = args.page_width // (args.card_width + 2 * args.card_bleed_x + args.spacing_x)
    rows_with_bleed = args.page_height // (args.card_height + 2 * args.card_bleed_y + args.spacing_y)

    cols = args.page_width // (args.card_width + args.spacing_x)
    rows = args.page_height // (args.card_height + args.spacing_y)

    page_capacity_bleed = cols_with_bleed * rows_with_bleed
    page_capacity = cols * rows


    pages_with_bleed = helpers.ceiling_divide(cards_with_bleed, page_capacity_bleed)
    pages_without_bleed = helpers.ceiling_divide(total_cards - pages_with_bleed * page_capacity_bleed, page_capacity)

    pages_with_backs = helpers.ceiling_divide(cards_with_backs, page_capacity_bleed)
    total_pages = int(pages_with_bleed + pages_without_bleed)

    return total_pages, pages_with_backs


def create_pages(args: CLIArgs, cards: list[DoubleSidedCard]) -> list[Page]:
    '''Create list of blank Pages'''
    total_pages, pages_with_backs = calculate_number_of_pages(cards, args)
    pages = [
        Page(args, has_back=(i < pages_with_backs))
        for i in range(total_pages)
    ]
    return pages


def populate_pages(args: CLIArgs, cards: list[DoubleSidedCard]):
    '''Creates pages and populates them with card images, then saves them as a jpg.

    Args:
        args (ArgumentParser): Object containing command-line arguments.
        cards (list of Card): list of Card objects
    '''
    pages = create_pages(args, cards)
    current_page = 1

    for card in cards:
        for _ in range(card.copies):
            page = pages[current_page - 1]

            if page.is_empty:
                print(f'Creating page {current_page}...')

            add_card_to_page(card, page)

            if page.is_full:
                if not args.save_as_pdf:
                    save_pages(page, str(current_page))
                else:
                    print()

                current_page += 1
                continue

    if args.save_as_pdf:
        save_pages_as_pdf(pages)
    else:
        if current_page <= len(pages):
            save_pages(pages[-1], str(current_page))


def main(argv=None):
    args = CLIArgsManager(argv).get_cli_args()
    clear_pages_folder()
    cards = create_cards(args)
    populate_pages(args, cards)


if __name__ == '__main__':
    main()
